# Generated by Django 3.2 on 2021-04-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210429_0304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='phone_num',
            new_name='mobile_num',
        ),
    ]
